import { CopyOutlined, DeleteOutlined, PlusOutlined, SaveOutlined } from '@ant-design/icons'
import dayjs, { type Dayjs } from 'dayjs'
import { Alert, Button, Card, DatePicker, Empty, InputNumber, Progress, Select, Space, Tag, Typography, message } from 'antd'
import { useEffect, useState } from 'react'
import { categoryApi } from '../api/categoriesApi'
import { budgetApi } from '../api/budgetsApi'
import type { BudgetResponse, CategoryResponse } from '../api/contracts'
import { ScopeToggle } from '../components/ScopeToggle'
import { useDataScope } from '../hooks/useDataScope'
import { useAuthStore } from '../stores/authStore'

export function BudgetsPage() {
  const familyId = useAuthStore((s) => s.familyId); const [scope] = useDataScope(); const [month, setMonth] = useState(dayjs().format('YYYY-MM')); const [budget, setBudget] = useState<BudgetResponse | null>(null); const [categories, setCategories] = useState<CategoryResponse[]>([]); const [total, setTotal] = useState(0); const [items, setItems] = useState<Record<number, number>>({}); const [api, holder] = message.useMessage()
  const load = async () => { if (!familyId) return; try { const [b, c] = await Promise.all([budgetApi.get(month, { family_id: Number(familyId), scope }), categoryApi.list({ family_id: Number(familyId), type: 'EXPENSE' })]); const data = b.data.data; setBudget(data); setTotal(Number(data?.total_amount ?? 0)); setItems(Object.fromEntries((data?.categories ?? []).map((i) => [i.category_id, Number(i.amount)]))); setCategories(c.data.data?.items ?? []) } catch { api.error('预算加载失败') } }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [familyId, scope, month])
  const save = async () => { if (!familyId) return; try { const r = await budgetApi.save(month, { family_id: Number(familyId), scope, total_amount: total.toFixed(2), categories: Object.entries(items).map(([category_id, amount]) => ({ category_id: Number(category_id), amount: amount.toFixed(2) })) }); setBudget(r.data.data); api.success('预算已保存') } catch { api.error('保存失败，请确认权限') } }
  const copy = async () => { if (!familyId) return; try { const r = await budgetApi.copyFromPrevious(month, { family_id: Number(familyId), scope }); setBudget(r.data.data); setTotal(Number(r.data.data?.total_amount ?? 0)); setItems(Object.fromEntries((r.data.data?.categories ?? []).map((i) => [i.category_id, Number(i.amount)]))); api.success('已复制上月预算') } catch { api.error('复制失败') } }
  const selected = Object.keys(items).map(Number); const available = categories.filter((c) => !c.deleted_at && !selected.includes(c.id)); const used = Number(budget?.used_amount ?? 0); const percent = total ? Math.round(used / total * 100) : 0
  return <div className="page">{holder}<div className="page-heading"><div><Typography.Title level={2}>月度预算</Typography.Title><Typography.Text>预算和执行数据均来自后端，个人预算仅当前成员可见。</Typography.Text></div><Space><ScopeToggle /><DatePicker picker="month" value={dayjs(month)} onChange={(v: Dayjs | null) => v && setMonth(v.format('YYYY-MM'))} /><Button icon={<CopyOutlined />} onClick={() => void copy()}>复制上月</Button><Button type="primary" icon={<SaveOutlined />} onClick={() => void save()}>保存预算</Button></Space></div><Card className="data-card" title="月度总预算"><Space align="center" wrap><InputNumber min={0} precision={2} value={total} onChange={(v) => setTotal(v ?? 0)} addonBefore="¥" /><span>已支出 ¥{used.toFixed(2)}</span><Progress percent={Math.min(percent, 100)} status={percent > 100 ? 'exception' : percent >= 80 ? 'active' : 'normal'} /></Space>{percent >= 80 && <Alert className="budget-alert" showIcon type={percent > 100 ? 'error' : 'warning'} message={percent > 100 ? '总预算已超支' : '预算使用达到预警线'} />}</Card><Card className="data-card" title="分类预算" extra={<Select placeholder="添加预算分类" value={undefined} onChange={(id: number) => setItems((old) => ({ ...old, [id]: 0 }))} options={available.map((c) => ({ value: c.id, label: `${c.icon ?? ''} ${c.name}` }))} suffixIcon={<PlusOutlined />} style={{ width: 180 }} />}>{selected.length === 0 ? <Empty description="当前月份暂无分类预算" /> : <div className="budget-list">{selected.map((id) => { const c = categories.find((x) => x.id === id); if (!c) return null; const item = budget?.categories.find((x) => x.category_id === id); const limit = items[id] ?? 0; const actual = Number(item?.used_amount ?? 0); const p = limit ? Math.round(actual / limit * 100) : 0; return <div className="budget-item" key={id}><div className="budget-item__heading"><Space><span className="category-dot category-dot--large" style={{ background: c.color ?? '#999' }} /><div><strong>{c.name}</strong><span>本月支出 ¥{actual.toFixed(2)}</span></div></Space><Space><InputNumber min={0} precision={2} value={limit} onChange={(v) => setItems((old) => ({ ...old, [id]: v ?? 0 }))} addonBefore="¥" /><Button type="text" danger icon={<DeleteOutlined />} onClick={() => setItems((old) => { const n = { ...old }; delete n[id]; return n })} /></Space></div><div className="budget-item__progress"><Progress percent={Math.min(p, 100)} status={p > 100 ? 'exception' : p >= 80 ? 'active' : 'normal'} /><Tag color={p > 100 ? 'red' : p >= 80 ? 'gold' : 'green'}>{p > 100 ? '超支' : p >= 80 ? '预警' : '正常'}</Tag></div></div> })}</div>}</Card></div>
}
