import { DeleteOutlined, EditOutlined, PlusOutlined } from '@ant-design/icons'
import { Button, Card, Drawer, Form, Input, Segmented, Space, Table, Tag, Typography, message } from 'antd'
import type { TableColumnsType } from 'antd'
import { useEffect, useState } from 'react'
import { categoryApi } from '../api/categoriesApi'
import type { CategoryResponse } from '../api/contracts'
import type { CategoryType } from '../data/financeData'
import { ScopeToggle } from '../components/ScopeToggle'
import { useAuthStore } from '../stores/authStore'
import axios from 'axios'

type FormValues = { name: string; type: CategoryType; color?: string; icon?: string }
export function CategoriesPage() {
  const familyId = useAuthStore((s) => s.familyId); const [type, setType] = useState<CategoryType>('EXPENSE'); const [categories, setCategories] = useState<CategoryResponse[]>([]); const [editing, setEditing] = useState<CategoryResponse | null>(null); const [open, setOpen] = useState(false); const [form] = Form.useForm<FormValues>(); const [api, holder] = message.useMessage()
  const load = async () => { if (!familyId) return; try { const r = await categoryApi.list({ family_id: Number(familyId), include_deleted: true, page_size: 100 }); setCategories(r.data.data?.items ?? []) } catch { api.error('分类加载失败') } }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [familyId])
  const submit = async (v: FormValues) => { if (!familyId) return; try { if (editing) await categoryApi.update(editing.id, { name: v.name, color: v.color, icon: v.icon }); else await categoryApi.create({ family_id: Number(familyId), name: v.name, type: v.type, color: v.color ?? '#58754d', icon: v.icon }); api.success(editing ? '分类已更新' : '分类已创建'); setOpen(false); await load() } catch (error: unknown) { const detail = axios.isAxiosError(error) ? error.response?.data?.message : undefined; api.error(detail || '保存失败，请检查管理员权限或输入') } }
  const displayed = categories.filter((c) => c.type === type)
  const columns: TableColumnsType<CategoryResponse> = [{ title: '分类', render: (_, c) => <Space><span className="category-dot category-dot--large" style={{ background: c.color ?? '#999' }} />{c.icon}<strong>{c.name}</strong></Space> }, { title: '类型', render: (_, c) => c.type === 'INCOME' ? '收入' : '支出' }, { title: '状态', render: (_, c) => c.deleted_at ? <Tag>保留历史</Tag> : <Tag color="green">可用</Tag> }, { title: '操作', render: (_, c) => <Space><Button type="text" icon={<EditOutlined />} disabled={!!c.deleted_at} onClick={() => { setEditing(c); form.setFieldsValue({ name: c.name, type: c.type, color: c.color ?? '', icon: c.icon ?? '' }); setOpen(true) }} /><Button type="text" danger icon={<DeleteOutlined />} disabled={!!c.deleted_at} onClick={async () => { try { await categoryApi.remove(c.id); api.success('分类已删除或停用'); await load() } catch { api.error('删除失败') } }} /></Space> }]
  return <div className="page">{holder}<div className="page-heading"><div><Typography.Title level={2}>分类管理</Typography.Title><Typography.Text>分类由家庭管理员维护，已引用分类删除后会保留历史名称。</Typography.Text></div><Space><ScopeToggle /><Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditing(null); form.resetFields(); form.setFieldsValue({ type, color: '#58754d', icon: '•' }); setOpen(true) }}>新增分类</Button></Space></div><Card className="filter-card" bordered={false}><Segmented value={type} onChange={(v) => setType(v as CategoryType)} options={[{ value: 'EXPENSE', label: '支出分类' }, { value: 'INCOME', label: '收入分类' }]} /></Card><Card className="data-card" title={`${type === 'INCOME' ? '收入' : '支出'}分类 · ${displayed.length} 项`}><Table rowKey="id" columns={columns} dataSource={displayed} pagination={false} /></Card><Drawer title={editing ? '编辑分类' : '新增分类'} open={open} onClose={() => setOpen(false)} width={420} footer={<Space className="drawer-actions"><Button onClick={() => setOpen(false)}>取消</Button><Button type="primary" onClick={() => form.submit()}>保存分类</Button></Space>}><Form form={form} layout="vertical" onFinish={submit}><Form.Item label="分类名称" name="name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item label="分类类型" name="type" rules={[{ required: true }]}><Segmented options={[{ value: 'EXPENSE', label: '支出' }, { value: 'INCOME', label: '收入' }]} disabled={!!editing} /></Form.Item><Form.Item label="图标" name="icon"><Input /></Form.Item><Form.Item label="颜色" name="color"><Input /></Form.Item></Form></Drawer></div>
}
