import { DeleteOutlined, PlusOutlined, ReloadOutlined, UserAddOutlined } from '@ant-design/icons'
import { Avatar, Button, Card, Form, Input, Modal, Popconfirm, Segmented, Space, Table, Tag, Typography, message } from 'antd'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { familyApi } from '../api/familiesApi'
import type { ApiResponse, FamilyMemberResponse, FamilySummary } from '../api/contracts'
import { useAuthStore } from '../stores/authStore'

export function FamilyPage() {
  const [families, setFamilies] = useState<FamilySummary[]>([])
  const [members, setMembers] = useState<FamilyMemberResponse[]>([])
  const [invite, setInvite] = useState<{ invite_code: string; expires_at: string } | null>(null)
  const [inviteOpen, setInviteOpen] = useState(false)
  const [joinOpen, setJoinOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [api, holder] = message.useMessage()
  const familyId = useAuthStore((state) => state.familyId)
  const currentUser = useAuthStore((state) => state.user)
  const setFamilyId = useAuthStore((state) => state.setFamily)
  const [createForm] = Form.useForm<{ name: string }>()
  const [joinForm] = Form.useForm<{ invite_code: string }>()
  const selected = useMemo(() => families.find((family) => String(family.id) === familyId), [families, familyId])
  const loadMembers = useCallback(async (id: string) => { try { const result = (await familyApi.members(id)).data; setMembers(result.data ?? []) } catch { api.error('成员列表加载失败') } }, [api])
  const loadFamilies = useCallback(async (preferredId?: string | null) => { setLoading(true); try { const result = (await familyApi.list()).data; const next = result.data ?? []; setFamilies(next); const target = preferredId && next.some((item) => String(item.id) === preferredId) ? preferredId : next[0] ? String(next[0].id) : null; setFamilyId(target); if (target) await loadMembers(target); else setMembers([]) } catch { api.error('家庭列表加载失败，请稍后重试') } finally { setLoading(false) } }, [api, loadMembers, setFamilyId])
  useEffect(() => { void loadFamilies(familyId) }, [familyId, loadFamilies])
  useEffect(() => { if (familyId) void loadMembers(familyId) }, [familyId, loadMembers])
  const createFamily = async ({ name }: { name: string }) => { try { const result = (await familyApi.create({ name })).data; if (result.data) { setFamilies((items) => [...items, result.data!]); setFamilyId(String(result.data.id)); await loadMembers(String(result.data.id)); createForm.resetFields(); api.success('家庭已创建，你已成为管理员') } } catch { api.error('创建家庭失败') } }
  const joinFamily = async ({ invite_code }: { invite_code: string }) => { try { const result = (await familyApi.join(invite_code.trim())).data; if (result.data) { setJoinOpen(false); joinForm.resetFields(); await loadFamilies(String(result.data.family_id)); api.success('已加入家庭') } } catch { api.error('邀请码无效或已过期') } }
  const generateInvite = async () => { if (!selected) return; try { const result = (await familyApi.createInvite(String(selected.id))).data as ApiResponse<{ invite_code: string; expires_at: string }>; if (result.data) { setInvite(result.data); setInviteOpen(true); api.success('邀请码已生成') } } catch { api.error('生成邀请码失败，请确认你是管理员') } }
  const updateRole = async (member: FamilyMemberResponse, role: 'ADMIN' | 'MEMBER') => { try { const result = (await familyApi.updateMember(String(member.family_id), String(member.id), role)).data as ApiResponse<FamilyMemberResponse>; if (result.data) setMembers((items) => items.map((item) => item.id === member.id ? result.data! : item)) } catch { api.error('角色更新失败') } }
  const removeMember = async (member: FamilyMemberResponse) => { if (!selected) return; try { await familyApi.removeMember(String(selected.id), String(member.id)); setMembers((items) => items.filter((item) => item.id !== member.id)); api.success('成员已移除') } catch { api.error('成员移除失败') } }
  return <div className="page">{holder}<div className="page-heading"><div><Typography.Title level={2}>家庭设置</Typography.Title><Typography.Text>切换账本、管理邀请码与成员角色，家庭数据相互隔离。</Typography.Text></div><Space><Button icon={<UserAddOutlined />} onClick={() => setJoinOpen(true)}>加入家庭</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => Modal.confirm({ title: '创建家庭', content: <Form form={createForm} layout="vertical"><Form.Item name="name" label="家庭名称" rules={[{ required: true, message: '请输入家庭名称' }]}><Input placeholder="例如：我们的家" /></Form.Item></Form>, onOk: () => createForm.validateFields().then(createFamily) })}>创建家庭</Button></Space></div><Card className="data-card" title="我的家庭" loading={loading}>{families.length ? <Segmented block value={familyId ?? undefined} onChange={(value) => setFamilyId(String(value))} options={families.map((family) => ({ value: String(family.id), label: family.name }))} /> : <Typography.Text type="secondary">还没有家庭，请先创建或加入一个家庭。</Typography.Text>}</Card>{selected && <Card className="data-card" title={`${selected.name} · 成员管理`} extra={<Space><Button icon={<ReloadOutlined />} onClick={generateInvite}>生成邀请码</Button><Button onClick={() => setInviteOpen(true)} disabled={!invite}>查看邀请码</Button></Space>}><Table rowKey="id" dataSource={members} pagination={false} columns={[{ title: '成员', render: (_, member) => <Space><Avatar src={member.avatar ?? undefined}>{member.nickname?.slice(0, 1) ?? '?'}</Avatar>{member.nickname ?? member.username}</Space> }, { title: '用户名', dataIndex: 'username' }, { title: '角色', render: (_, member) => <Tag color={member.role === 'ADMIN' ? 'blue' : 'default'}>{member.role === 'ADMIN' ? '管理员' : '成员'}</Tag> }, { title: '加入时间', dataIndex: 'joined_at', render: (value: string) => value?.slice(0, 10) }, { title: '操作', render: (_, member) => <Space>{String(member.user_id) !== String(currentUser?.id) && <Segmented size="small" value={member.role} options={[{ label: '成员', value: 'MEMBER' }, { label: '管理员', value: 'ADMIN' }]} onChange={(value) => void updateRole(member, value as 'ADMIN' | 'MEMBER')} />}<Popconfirm title="移除该成员？" onConfirm={() => void removeMember(member)}><Button danger type="text" icon={<DeleteOutlined />} /></Popconfirm></Space> }]} /></Card>}<Modal title="家庭邀请码" open={inviteOpen} onCancel={() => setInviteOpen(false)} footer={<Button onClick={() => setInviteOpen(false)}>关闭</Button>}>{invite ? <><Typography.Title level={3}>{invite.invite_code}</Typography.Title><Typography.Text type="secondary">有效期至 {new Date(invite.expires_at).toLocaleString('zh-CN')}</Typography.Text></> : <Typography.Text type="secondary">暂无有效邀请码，请先生成。</Typography.Text>}</Modal><Modal title="加入家庭" open={joinOpen} onCancel={() => setJoinOpen(false)} onOk={() => joinForm.validateFields().then(joinFamily)}><Form form={joinForm} layout="vertical"><Form.Item name="invite_code" label="邀请码" rules={[{ required: true, message: '请输入邀请码' }]}><Input placeholder="请输入邀请码" /></Form.Item></Form></Modal></div>
}
