import { InboxOutlined } from '@ant-design/icons'
import { Alert, Button, Card, Input, Select, Space, Steps, Table, Tag, Typography, Upload, message } from 'antd'
import type { UploadProps } from 'antd'
import { useEffect, useState } from 'react'
import { importApi } from '../api/importsApi'
import { accountApi } from '../api/accountsApi'
import { categoryApi } from '../api/categoriesApi'
import { familyApi } from '../api/familiesApi'
import type { CategoryResponse } from '../api/contracts'
import { useAuthStore } from '../stores/authStore'
import { ScopeToggle } from '../components/ScopeToggle'
import { useDataScope } from '../hooks/useDataScope'

type NormalizedData = { occurred_at?: string; type?: string; amount?: string; category_id?: number | null; category_name?: string; remark?: string; beneficiary_member_id?: number }
type BatchRow = { row_number: number; validation_status: 'VALID' | 'INVALID' | 'DUPLICATE' | 'SKIPPED'; normalized_data?: NormalizedData; errors?: string[] }
type Batch = { batch_id: number; file_name: string; status: string; total_rows: number; valid_rows: number; invalid_rows: number; duplicate_rows: number; rows: BatchRow[] }

export function ImportsPage() {
  const familyId = useAuthStore(s => s.familyId); const [scope] = useDataScope(); const [api, holder] = message.useMessage()
  const [accounts, setAccounts] = useState<Array<{ id: number; name: string; closed_at: string | null; owner_member_id?: number }>>([]); const [categories, setCategories] = useState<CategoryResponse[]>([]); const [memberId, setMemberId] = useState<number>(); const [accountId, setAccountId] = useState<number>(); const [selectedFile, setSelectedFile] = useState<File>(); const [step, setStep] = useState(0); const [batch, setBatch] = useState<Batch>(); const [loading, setLoading] = useState(false)
  useEffect(() => { if (!familyId) return; Promise.all([accountApi.list({ family_id: Number(familyId), scope: 'family', include_closed: false, page_size: 100 }), familyApi.members(familyId), categoryApi.list({ family_id: Number(familyId), include_deleted: false, page_size: 100 })]).then(([a, m, c]) => { setAccounts((a.data.data?.items ?? []) as typeof accounts); const found = (m.data.data ?? []).find(x => String(x.user_id) === String(useAuthStore.getState().user?.id)); if (found) setMemberId(Number(found.id)); setCategories(c.data.data?.items ?? []) }).catch(() => api.error('账户或分类加载失败')) }, [familyId, api])
  const uploadProps: UploadProps = { accept: '.csv,.xlsx', showUploadList: false, beforeUpload: file => { setSelectedFile(file); setStep(1); return false } }
  const preview = async () => { if (!familyId || !accountId || !selectedFile) return; setLoading(true); try { const res = await importApi.preview({ family_id: Number(familyId), scope, account_id: accountId, file: selectedFile }); setBatch(res.data.data as Batch); setStep(2) } catch { api.error('文件解析失败，请检查格式和字段') } finally { setLoading(false) } }
  const updateCell = (rowNumber: number, field: keyof NormalizedData, value: unknown) => setBatch(current => current ? ({ ...current, rows: current.rows.map(row => row.row_number === rowNumber ? { ...row, normalized_data: { ...(row.normalized_data ?? {}), [field]: value } } : row) }) : current)
  const saveRows = async () => { if (!batch) return; setLoading(true); try { const res = await importApi.updateRows(batch.batch_id, batch.rows.map(row => ({ row_number: row.row_number, normalized_data: row.normalized_data ?? {} }))); setBatch(res.data.data as Batch); api.success('预览修改已保存，请检查状态后确认') } catch { api.error('保存修改失败，请检查填写内容') } finally { setLoading(false) } }
  const confirm = async () => { if (!batch) return; setLoading(true); try { await importApi.confirm(batch.batch_id); api.success('导入成功'); setBatch({ ...batch, status: 'CONFIRMED' }) } catch { api.error('导入失败，请先保存并修正无效行') } finally { setLoading(false) } }
  const categoryOptions = (type?: string) => categories.filter(c => !c.deleted_at && c.type === type).map(c => ({ value: c.id, label: c.name }))
  const statusTag = (status: BatchRow['validation_status']) => <Tag color={status === 'VALID' ? 'green' : status === 'DUPLICATE' ? 'gold' : status === 'SKIPPED' ? 'default' : 'red'}>{status === 'VALID' ? '有效' : status === 'DUPLICATE' ? '重复' : status === 'SKIPPED' ? '已跳过' : '待补充'}</Tag>
  return <div className="page">{holder}<div className="page-heading"><div><Typography.Title level={2}>账单导入</Typography.Title><Typography.Text>上传 CSV/XLSX，补充未知字段后保存预览，再确认写入流水。</Typography.Text></div><ScopeToggle /></div><Card className="data-card"><Steps current={step} items={[{ title: '选择账户与来源' }, { title: '上传文件' }, { title: '预览并确认' }]} /></Card>
    {step === 0 && <Card className="data-card" title="1. 选择目标账户"><Select placeholder="选择目标账户" value={accountId} onChange={setAccountId} options={accounts.filter(a => scope === 'family' || a.owner_member_id === memberId).map(a => ({ value: a.id, label: a.name }))} style={{ width: 300 }} /><div style={{ marginTop: 24 }}><Upload.Dragger {...uploadProps} disabled={!accountId}><p className="ant-upload-drag-icon"><InboxOutlined /></p><p>选择 CSV 或 XLSX 文件</p><p className="ant-upload-hint">支持支付宝、微信账单及常见中文/英文表头。</p></Upload.Dragger></div></Card>}
    {step === 1 && <Card className="data-card" title="2. 上传文件"><Alert message={`已选择 ${selectedFile?.name ?? '文件'}`} showIcon /><Space style={{ marginTop: 20 }}><Button onClick={() => setStep(0)}>返回</Button><Button type="primary" onClick={preview} loading={loading}>生成预览</Button></Space></Card>}
    {step === 2 && batch && <Card className="data-card" title="3. 预览、补充并确认" extra={<Space><Button onClick={saveRows} loading={loading}>保存修改</Button><Button onClick={() => { setStep(0); setBatch(undefined); setSelectedFile(undefined) }}>重新选择</Button></Space>}><Space style={{ marginBottom: 16 }}><Tag color="green">有效 {batch.valid_rows}</Tag><Tag color="gold">重复 {batch.duplicate_rows}</Tag><Tag color="red">待补充 {batch.invalid_rows}</Tag></Space><Table rowKey="row_number" dataSource={batch.rows} pagination={{ pageSize: 10 }} scroll={{ x: 1100 }} columns={[{ title: '行号', dataIndex: 'row_number', width: 70 }, { title: '发生时间', width: 190, render: (_: unknown, r: BatchRow) => r.validation_status === 'SKIPPED' ? '不计收支' : <Input size="small" value={r.normalized_data?.occurred_at ?? '未知'} onChange={e => updateCell(r.row_number, 'occurred_at', e.target.value)} /> }, { title: '类型', width: 100, render: (_: unknown, r: BatchRow) => r.validation_status === 'SKIPPED' ? '-' : <Select size="small" value={r.normalized_data?.type} onChange={value => updateCell(r.row_number, 'type', value)} options={[{ value: 'EXPENSE', label: '支出' }, { value: 'INCOME', label: '收入' }]} /> }, { title: '金额', width: 120, render: (_: unknown, r: BatchRow) => r.validation_status === 'SKIPPED' ? '-' : <Input size="small" value={r.normalized_data?.amount ?? ''} onChange={e => updateCell(r.row_number, 'amount', e.target.value)} placeholder="未知" /> }, { title: '分类', width: 130, render: (_: unknown, r: BatchRow) => r.validation_status === 'SKIPPED' ? '-' : <Select size="small" value={r.normalized_data?.category_id ?? undefined} placeholder={r.normalized_data?.category_name ?? '选择分类'} onChange={value => updateCell(r.row_number, 'category_id', value)} options={categoryOptions(r.normalized_data?.type)} /> }, { title: '备注', width: 240, render: (_: unknown, r: BatchRow) => r.validation_status === 'SKIPPED' ? (r.normalized_data?.remark ?? '不计收支') : <Input size="small" value={r.normalized_data?.remark ?? '未知'} onChange={e => updateCell(r.row_number, 'remark', e.target.value)} /> }, { title: '状态', width: 90, render: (_: unknown, r: BatchRow) => statusTag(r.validation_status) }, { title: '提示', render: (_: unknown, r: BatchRow) => r.errors?.join('、') }]} /><Button type="primary" style={{ marginTop: 20 }} disabled={batch.invalid_rows > 0 || batch.status !== 'PREVIEWED'} loading={loading} onClick={confirm}>确认导入有效行</Button></Card>}
  </div>
}
