import ReactECharts from 'echarts-for-react'
import type { EChartsOption } from 'echarts'
import dayjs, { type Dayjs } from 'dayjs'
import { Alert, Card, DatePicker, Empty, Flex, Skeleton, Space, Statistic, Tabs, Typography } from 'antd'
import { useEffect, useMemo, useState } from 'react'
import { reportApi } from '../api/reportsApi'
import { formatCurrency } from '../data/financeData'
import { ScopeToggle } from '../components/ScopeToggle'
import { useDataScope } from '../hooks/useDataScope'
import { useAuthStore } from '../stores/authStore'

type Summary = { income: number; expense: number; balance: number }
type TrendPoint = { month: string; income: number; expense: number }
type CategoryPoint = { category_name: string; amount: number }
type MemberPoint = { member_id: number; member_name: string; income: number; expense: number; assets: number; transferIn: number; transferOut: number }
const emptySummary: Summary = { income: 0, expense: 0, balance: 0 }
function parseSummary(value: unknown): Summary { const s = (value as { data?: { data?: Record<string, string> } })?.data?.data ?? {}; return { income: Number(s.income ?? 0), expense: Number(s.expense ?? 0), balance: Number(s.balance ?? 0) } }
function parseList<T>(value: unknown, map: (item: Record<string, string>) => T): T[] { const data = (value as { data?: { data?: Array<Record<string, string>> } })?.data?.data ?? []; return data.map(map) }

export function ReportsPage() {
  const [month, setMonth] = useState(() => dayjs().format('YYYY-MM')); const [mode] = useDataScope(); const familyId = useAuthStore((state) => state.familyId)
  const [summary, setSummary] = useState<Summary>(emptySummary); const [trend, setTrend] = useState<TrendPoint[]>([]); const [categories, setCategories] = useState<CategoryPoint[]>([]); const [members, setMembers] = useState<MemberPoint[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => {
    if (!familyId) { setError('请先选择家庭'); return }
    const id = Number(familyId); const fromMonth = dayjs(`${month}-01`).subtract(5, 'month').format('YYYY-MM'); setLoading(true); setError(null)
    const requests = mode === 'family' ? Promise.all([reportApi.familySummary({ family_id: id, month }), reportApi.familyTrend({ family_id: id, from_month: fromMonth, to_month: month }), reportApi.familyByCategory({ family_id: id, month }), reportApi.familyByMember({ family_id: id, month })]) : Promise.all([reportApi.personalSummary({ family_id: id, from_date: `${month}-01`, to_date: `${month}-${dayjs(`${month}-01`).daysInMonth()}` }), reportApi.personalTrend({ family_id: id, from_month: fromMonth, to_month: month }), reportApi.personalByCategory({ family_id: id, month })])
    requests.then((result) => { setSummary(parseSummary(result[0])); setTrend(parseList(result[1], (x) => ({ month: x.month, income: Number(x.income ?? 0), expense: Number(x.expense ?? 0) }))); setCategories(parseList(result[2], (x) => ({ category_name: x.category_name, amount: Number(x.amount ?? 0) }))); setMembers(mode === 'family' ? parseList(result[3], (x) => ({ member_id: Number(x.member_id), member_name: x.member_name, income: Number(x.income ?? 0), expense: Number(x.expense ?? 0), assets: Number(x.assets ?? 0), transferIn: Number(x.transfer_in ?? 0), transferOut: Number(x.transfer_out ?? 0) })) : []) }).catch(() => setError('报表接口暂时不可用，请稍后重试')).finally(() => setLoading(false))
  }, [familyId, mode, month])
  const trendOption: EChartsOption = useMemo(() => ({ tooltip: { trigger: 'axis', valueFormatter: (v) => formatCurrency(Number(v)) }, legend: { data: ['收入', '支出', '结余'] }, xAxis: { type: 'category', data: trend.map((x) => x.month) }, yAxis: { type: 'value' }, series: [{ name: '收入', type: 'line', smooth: true, data: trend.map((x) => x.income), itemStyle: { color: '#3f8f62' } }, { name: '支出', type: 'line', smooth: true, data: trend.map((x) => x.expense), itemStyle: { color: '#c85b4b' } }, { name: '结余', type: 'line', smooth: true, data: trend.map((x) => x.income - x.expense), itemStyle: { color: '#5579a7' } }] }), [trend])
  const pieOption: EChartsOption = useMemo(() => ({ tooltip: { trigger: 'item', valueFormatter: (v) => formatCurrency(Number(v)) }, series: [{ type: 'pie', radius: ['48%', '72%'], label: { formatter: '{b}\n{d}%' }, data: categories.map((x) => ({ name: x.category_name, value: x.amount })) }] }), [categories])
  const memberOption: EChartsOption = useMemo(() => ({ tooltip: { trigger: 'axis', valueFormatter: (v) => formatCurrency(Number(v)) }, legend: { data: ['收入', '支出', '资产', '转入', '转出'] }, grid: { left: 52, right: 24, top: 42, bottom: 44 }, xAxis: { type: 'category', data: members.map((m) => m.member_name), axisLabel: { interval: 0 } }, yAxis: { type: 'value' }, series: [{ name: '收入', type: 'bar', data: members.map((m) => m.income), itemStyle: { color: '#3f8f62' } }, { name: '支出', type: 'bar', data: members.map((m) => m.expense), itemStyle: { color: '#c85b4b' } }, { name: '资产', type: 'bar', data: members.map((m) => m.assets), itemStyle: { color: '#5579a7' } }, { name: '转入', type: 'bar', data: members.map((m) => m.transferIn), itemStyle: { color: '#b88426' } }, { name: '转出', type: 'bar', data: members.map((m) => m.transferOut), itemStyle: { color: '#8a6fb5' } }] }), [members])
  const change = (value: Dayjs | null) => value && setMonth(value.format('YYYY-MM'))
  return <div className="page"><div className="page-heading"><div><Typography.Title level={2}>数据报表</Typography.Title><Typography.Text>按月查看收支趋势、分类构成和家庭成员对比。</Typography.Text></div><Space><ScopeToggle /><DatePicker picker="month" value={dayjs(`${month}-01`)} onChange={change} allowClear={false} /></Space></div>{error && <Alert type="warning" showIcon message={error} style={{ marginBottom: 16 }} />}{loading ? <Skeleton active paragraph={{ rows: 7 }} /> : <><Card className="data-card"><Flex gap={48} wrap="wrap"><Statistic title={mode === 'family' ? '家庭收入' : '个人收入'} value={summary.income} formatter={(v) => formatCurrency(Number(v))} /><Statistic title={mode === 'family' ? '家庭支出' : '个人支出'} value={summary.expense} formatter={(v) => formatCurrency(Number(v))} /><Statistic title="结余" value={summary.balance} formatter={(v) => formatCurrency(Number(v))} /></Flex></Card>{!trend.length && !categories.length ? <Card className="data-card"><Empty description="当前月份暂无可分析数据" /></Card> : <Tabs items={[{ key: 'trend', label: '月度趋势', children: <Card className="data-card"><ReactECharts option={trendOption} style={{ height: 320 }} /></Card> }, { key: 'category', label: '分类占比', children: <Card className="data-card"><ReactECharts option={pieOption} style={{ height: 320 }} /></Card> }, ...(mode === 'family' ? [{ key: 'members', label: '成员对比', children: <Card className="data-card"><ReactECharts option={memberOption} style={{ height: 380 }} /></Card> }] : [])]} />}</>}</div>
}
