import { DeleteOutlined, EditOutlined, PlusOutlined } from '@ant-design/icons'
import dayjs, { type Dayjs } from 'dayjs'
import { Button, Card, DatePicker, Drawer, Form, Input, InputNumber, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd'
import type { TableColumnsType } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { transferApi, type TransferPayload } from '../api/transfersApi'
import { accountApi } from '../api/accountsApi'
import { familyApi } from '../api/familiesApi'
import type { AccountResponse, FamilyMemberResponse, TransferResponse } from '../api/contracts'
import { ScopeToggle } from '../components/ScopeToggle'
import { useDataScope } from '../hooks/useDataScope'
import { useAuthStore } from '../stores/authStore'

type Values = { from_account_id: number; to_account_id: number; amount: number; occurred_at: Dayjs; remark?: string }
export function TransfersPage() {
  const familyId = useAuthStore((s) => s.familyId); const [scope] = useDataScope(); const [form] = Form.useForm<Values>(); const [items, setItems] = useState<TransferResponse[]>([]); const [accounts, setAccounts] = useState<AccountResponse[]>([]); const [members, setMembers] = useState<FamilyMemberResponse[]>([]); const [editingId, setEditingId] = useState<number>(); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [api, holder] = message.useMessage(); const user = useAuthStore((s) => s.user); const member = members.find((m) => String(m.user_id) === String(user?.id)); const isAdmin = user?.role === 'ADMIN' || member?.role === 'ADMIN'; const active = accounts.filter((a) => !a.closed_at); const outgoing = active.filter((a) => isAdmin || a.owner_member_id === member?.id); const fromId = Form.useWatch('from_account_id', form)
  const load = useCallback(async () => { if (!familyId) return; setLoading(true); try { const [tr, ac, ms] = await Promise.all([transferApi.list({ family_id: Number(familyId), scope, page: 1, page_size: 100 }), accountApi.list({ family_id: Number(familyId), scope: 'family', include_closed: true, page_size: 100 }), familyApi.members(familyId)]); setItems(tr.data.data?.items ?? []); setAccounts(ac.data.data?.items ?? []); setMembers(ms.data.data ?? []) } catch { api.error('转账加载失败') } finally { setLoading(false) } }, [api, familyId, scope]); useEffect(() => { void load() }, [load])
  const save = async (v: Values) => { if (!familyId || v.from_account_id === v.to_account_id) { api.error('转出和转入账户不能相同'); return }; const payload: TransferPayload = { family_id: Number(familyId), from_account_id: v.from_account_id, to_account_id: v.to_account_id, amount: v.amount.toFixed(2), occurred_at: v.occurred_at.format('YYYY-MM-DDTHH:mm:00Z'), remark: v.remark?.trim() || undefined }; try { if (editingId) await transferApi.update(editingId, { from_account_id: payload.from_account_id, to_account_id: payload.to_account_id, amount: payload.amount, occurred_at: payload.occurred_at, remark: payload.remark }); else await transferApi.create(payload); api.success(editingId ? '转账已更新' : '转账已创建，未计入收支统计'); setOpen(false); await load() } catch { api.error('保存失败，请检查账户、余额和权限') } }
  const remove = async (id: number) => { try { await transferApi.remove(id); api.success('转账已删除，双方余额已恢复'); await load() } catch { api.error('删除失败') } }
  const confirm = async (id: number) => { try { await transferApi.confirm(id); api.success('转账已确认，双方余额已更新'); await load() } catch { api.error('确认失败，仅转入方可以确认') } }
  const columns: TableColumnsType<TransferResponse> = [{ title: '发生时间', dataIndex: 'occurred_at', render: (v: string) => dayjs(v).format('YYYY-MM-DD HH:mm') }, { title: '转出', render: (_, t) => `${t.from_account_name ?? `账户 #${t.from_account_id}`} · ${t.from_member_nickname ?? '未知成员'}` }, { title: '转入', render: (_, t) => `${t.to_account_name ?? `账户 #${t.to_account_id}`} · ${t.to_member_nickname ?? '未知成员'}` }, { title: '金额', align: 'right', render: (_, t) => `¥${Number(t.amount).toFixed(2)}` }, { title: '状态', render: (_, t) => t.status === 'PENDING_CONFIRM' ? <Tag color="gold">待转入方确认</Tag> : <Tag color="green">已确认</Tag> }, { title: '录入人', render: (_, t) => t.recorder_nickname ?? `用户 #${t.recorder_user_id}` }, { title: '备注', dataIndex: 'remark', ellipsis: true }, { title: '操作', render: (_, t) => <Space size={0}>{t.status === 'PENDING_CONFIRM' && String(member?.id) === String(t.to_member_id) && <Button type="primary" size="small" onClick={() => void confirm(t.id)}>确认</Button>} {t.status === 'CONFIRMED' && <Button type="text" icon={<EditOutlined />} onClick={() => { setEditingId(t.id); form.setFieldsValue({ from_account_id: t.from_account_id, to_account_id: t.to_account_id, amount: Number(t.amount), occurred_at: dayjs(t.occurred_at), remark: t.remark ?? '' }); setOpen(true) }} />}<Popconfirm title="删除转账？" description="删除后会反向恢复两个账户余额。" onConfirm={() => void remove(t.id)}><Button type="text" danger icon={<DeleteOutlined />} /></Popconfirm></Space> }]
  return <div className="page">{holder}<div className="page-heading"><div><Typography.Title level={2}>账户转账</Typography.Title><Typography.Text>转账仅在两个账户间移动资金，不影响收入、支出、结余和预算。</Typography.Text></div><Space><ScopeToggle /><Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditingId(undefined); form.resetFields(); form.setFieldsValue({ occurred_at: dayjs() }); setOpen(true) }}>新增转账</Button></Space></div><Card loading={loading} className="data-card" title={`转账记录 · ${items.length} 笔`}><Table rowKey="id" columns={columns} dataSource={items} scroll={{ x: 950 }} pagination={{ pageSize: 10 }} /></Card><Drawer title={editingId ? '编辑账户转账' : '新增账户转账'} open={open} onClose={() => setOpen(false)} width={430} footer={<Space className="drawer-actions"><Button onClick={() => setOpen(false)}>取消</Button><Button type="primary" onClick={() => form.submit()}>保存</Button></Space>}><Form form={form} layout="vertical" onFinish={save}><Form.Item label="转出账户" name="from_account_id" rules={[{ required: true }]}><Select options={outgoing.map((a) => ({ value: a.id, label: `${a.name} · ¥${Number(a.current_balance).toFixed(2)}` }))} /></Form.Item><Form.Item label="转入账户" name="to_account_id" rules={[{ required: true }]}><Select options={active.filter((a) => a.id !== fromId).map((a) => ({ value: a.id, label: `${a.name} · ${members.find((m) => m.id === a.owner_member_id)?.nickname ?? ''}` }))} /></Form.Item><Form.Item label="金额" name="amount" rules={[{ required: true }, { type: 'number', min: 0.01, message: '金额必须大于 0' }]}><InputNumber min={0.01} precision={2} addonBefore="¥" className="full-width" /></Form.Item><Form.Item label="发生时间" name="occurred_at" rules={[{ required: true }]}><DatePicker showTime={{ format: 'HH:mm' }} format="YYYY-MM-DD HH:mm" className="full-width" /></Form.Item><Form.Item label="备注" name="remark"><Input.TextArea rows={3} maxLength={500} showCount /></Form.Item></Form></Drawer></div>
}
