import { DeleteOutlined, EditOutlined, ExportOutlined, PlusOutlined } from '@ant-design/icons'
import dayjs, { type Dayjs } from 'dayjs'
import { Button, Card, DatePicker, Drawer, Form, Input, InputNumber, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { transactionApi, type CreateTransactionPayload } from '../api/transactionsApi'
import { accountApi } from '../api/accountsApi'
import { categoryApi } from '../api/categoriesApi'
import { familyApi } from '../api/familiesApi'
import type { AccountResponse, CategoryResponse, FamilyMemberResponse, TransactionResponse } from '../api/contracts'
import { ScopeToggle } from '../components/ScopeToggle'
import { useDataScope } from '../hooks/useDataScope'
import { useAuthStore } from '../stores/authStore'

type Values = { type: 'INCOME' | 'EXPENSE'; account_id: number; category_id: number; beneficiary_member_id: number | string; amount: number; occurred_at: Dayjs; remark?: string }
export function TransactionsPage() {
  const familyId = useAuthStore((s) => s.familyId); const user = useAuthStore((s) => s.user); const [scope] = useDataScope(); const [form] = Form.useForm<Values>(); const [items, setItems] = useState<TransactionResponse[]>([]); const [accounts, setAccounts] = useState<AccountResponse[]>([]); const [categories, setCategories] = useState<CategoryResponse[]>([]); const [members, setMembers] = useState<FamilyMemberResponse[]>([]); const [editingId, setEditingId] = useState<number>(); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [api, holder] = message.useMessage()
  const member = members.find((m) => String(m.user_id) === String(user?.id)); const isAdmin = user?.role === 'ADMIN' || member?.role === 'ADMIN'; const activeAccounts = accounts.filter((a) => !a.closed_at && (isAdmin || a.owner_member_id === member?.id)); const activeCategories = categories.filter((c) => !c.deleted_at); const type = Form.useWatch('type', form) ?? 'EXPENSE'
  const load = useCallback(async () => { if (!familyId) return; setLoading(true); try { const [tx, ac, cats, ms] = await Promise.all([transactionApi.list({ family_id: familyId, scope, page: 1, page_size: 100 }), accountApi.list({ family_id: Number(familyId), scope: 'family', include_closed: true, page_size: 100 }), categoryApi.list({ family_id: Number(familyId), include_deleted: true, page_size: 100 }), familyApi.members(familyId)]); setItems(tx.data.data?.items ?? []); setAccounts(ac.data.data?.items ?? []); setCategories(cats.data.data?.items ?? []); setMembers(ms.data.data ?? []) } catch { api.error('流水加载失败') } finally { setLoading(false) } }, [api, familyId, scope]); useEffect(() => { void load() }, [load])
  const save = async (v: Values) => { if (!familyId) return; const p: CreateTransactionPayload = { family_id: Number(familyId), account_id: v.account_id, category_id: v.category_id, beneficiary_member_id: v.beneficiary_member_id, type: v.type, amount: v.amount.toFixed(2), occurred_at: v.occurred_at.format('YYYY-MM-DDTHH:mm:00Z'), remark: v.remark?.trim() || undefined }; try { if (editingId) await transactionApi.update(editingId, { account_id: p.account_id, category_id: p.category_id, beneficiary_member_id: p.beneficiary_member_id, amount: p.amount, occurred_at: p.occurred_at, remark: p.remark }); else await transactionApi.create(p); api.success(editingId ? '修改已提交，等待资金归属人确认' : '流水已创建'); setOpen(false); await load() } catch { api.error('保存失败') } }
  const columns = [{ title: '发生时间', dataIndex: 'occurred_at', render: (v: string) => dayjs(v).format('YYYY-MM-DD HH:mm') }, { title: '类型', dataIndex: 'type', render: (v: string) => <Tag color={v === 'INCOME' ? 'green' : 'volcano'}>{v === 'INCOME' ? '收入' : '支出'}</Tag> }, { title: '账户', render: (_: unknown, t: TransactionResponse) => t.account_name }, { title: '金额', render: (_: unknown, t: TransactionResponse) => `¥${Number(t.pending_update?.amount ?? t.amount).toFixed(2)}` }, { title: '状态', render: (_: unknown, t: TransactionResponse) => t.status === 'PENDING_CONFIRM' ? <Tag color="gold">待确认</Tag> : <Tag color="green">已确认</Tag> }, { title: '操作', render: (_: unknown, t: TransactionResponse) => <Space>{t.status === 'PENDING_CONFIRM' && String(member?.id) === String(t.beneficiary_member_id) && <Button type="primary" size="small" onClick={() => transactionApi.confirm(t.id).then(load).then(() => api.success('已确认')).catch(() => api.error('确认失败'))}>确认修改</Button>}{t.status !== 'PENDING_CONFIRM' && <Button type="text" icon={<EditOutlined />} onClick={() => { setEditingId(t.id); form.setFieldsValue({ type: t.type, account_id: t.account_id, category_id: t.category_id, beneficiary_member_id: t.beneficiary_member_id, amount: Number(t.amount), occurred_at: dayjs(t.occurred_at), remark: t.remark ?? '' }); setOpen(true) }} />}<Popconfirm title="删除这笔流水？" onConfirm={() => transactionApi.remove(t.id).then(load).catch(() => api.error('删除失败'))}><Button type="text" danger icon={<DeleteOutlined />} /></Popconfirm></Space> }]
  return <div className="page">{holder}<div className="page-heading"><div><Typography.Title level={2}>收支流水</Typography.Title><Typography.Text>管理员修改其他成员流水后，须由资金归属人确认才会更新余额。</Typography.Text></div><Space><ScopeToggle /><Button icon={<ExportOutlined />}>导出</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditingId(undefined); form.resetFields(); form.setFieldsValue({ type: 'EXPENSE', occurred_at: dayjs(), beneficiary_member_id: member?.id }); setOpen(true) }}>新增流水</Button></Space></div><Card loading={loading} className="data-card"><Table rowKey="id" columns={columns} dataSource={items} pagination={{ pageSize: 10 }} /></Card><Drawer title={editingId ? '编辑收支流水' : '新增收支流水'} open={open} onClose={() => setOpen(false)} footer={<Button type="primary" onClick={() => form.submit()}>保存</Button>}><Form form={form} layout="vertical" onFinish={save}><Form.Item label="流水类型" name="type" rules={[{ required: true }]}><Select disabled={!!editingId} options={[{ value: 'INCOME', label: '收入' }, { value: 'EXPENSE', label: '支出' }]} /></Form.Item><Form.Item label="金额" name="amount" rules={[{ required: true }, { type: 'number', min: 0.01 }]}><InputNumber min={0.01} precision={2} className="full-width" /></Form.Item><Form.Item label="账户" name="account_id" rules={[{ required: true }]}><Select options={activeAccounts.map((a) => ({ value: a.id, label: a.name }))} /></Form.Item><Form.Item label="分类" name="category_id" rules={[{ required: true }]}><Select options={activeCategories.filter((c) => c.type === type).map((c) => ({ value: c.id, label: c.name }))} /></Form.Item><Form.Item label="资金归属人" name="beneficiary_member_id" rules={[{ required: true }]}><Select disabled={!isAdmin} options={members.map((m) => ({ value: m.id, label: m.nickname ?? m.username }))} /></Form.Item><Form.Item label="发生时间" name="occurred_at" rules={[{ required: true }]}><DatePicker showTime={{ format: 'HH:mm' }} format="YYYY-MM-DD HH:mm" className="full-width" /></Form.Item><Form.Item label="备注" name="remark"><Input.TextArea rows={3} /></Form.Item></Form></Drawer></div>
}
